move name validation to route deserialization
NetsBlox/cloud pull request #253
Opened 2024-06-16 18:58 UTC by samankittani

this pr moves name validation to serde deserialization step

2024-07-04 13:21 UTC, brollb requested changes
Thanks, @samankittani ! Nice work. 

I added one comment about how we should be able to simplify the implementation of the different name validation. Otherwise, looks good!

2024-07-04 13:21 UTC, brollb commented on crates/api-common/src/lib.rs
> +pub struct Name<T: Validate>(String, std::marker::PhantomData<T>);
Why are we re-using this struct for all the different types of names rather than creating completely different versions for each (ie, `struct GroupName` rather than `type GroupName = ..`)? Is it just for code re-use?

If so, I am concerned that this approach introduces complexity that doesn't buy us much. For example, we could `impl Validate` for each of the `GroupName`, etc, structs (as opposed to type aliases) then define a blanket implementation for all structs that implement `Validate`.

2024-07-25 10:38 UTC, brollb commented on crates/cli/src/main.rs
> +#[allow(clippy::too_many_lines)]
Let's leave these clippy warnings in here and just try to satisfy them :)

2024-07-25 10:38 UTC, brollb commented on crates/cloud-common/src/lib.rs
> +    #[must_use]
why is this `must_use`?

2024-07-25 11:03 UTC, brollb commented
I went through and tried to make some bits of it more consistent. A couple comments:
- I haven't finished using `Username`, etc, everywhere in the cli, api, etc, so the build is broken
- I think there is a better way to implement the constraints rather than a phantom type (using `nutype` or something). One approach could be to implement `TryFrom<String>` for all the newtypes and then you could deserialize them pretty easily: use the `String` deserializer and call `TryFrom<String>` for the given type.

2024-07-30 04:25 UTC, samankittani commented on crates/cli/src/main.rs
> +#[allow(clippy::too_many_lines)]
gotcha! Thanks:)

2025-03-25 16:57 UTC, closed without merging